In [ ]:
%pip install oracledb

Collecting oracledb
  Downloading oracledb-26.0.1-cp312-cp312-win_amd64.whl.metadata (8.3 kB)
Collecting cryptography>=3.2.1 (from oracledb)
  Downloading cryptography-50.0.1-cp311-abi3-win_amd64.whl.metadata (4.3 kB)
Requirement already satisfied: typing_extensions>=4.14.0 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from oracledb) (4.16.0)
Collecting cffi>=2.0.0 (from cryptography>=3.2.1->oracledb)
  Downloading cffi-2.1.1-cp312-cp312-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography>=3.2.1->oracledb)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Downloading oracledb-26.0.1-cp312-cp312-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.0 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 6.8 MB/s eta 0:00:00
Downloading cryptography-50.0.1-cp311-abi3-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   -------------------------------------- - 3.7/3.8 MB 18.1 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 16.4 MB/s eta 0:00:00
Downloading cffi-2.1.1-cp312-cp312-win_amd64.whl (185 kB)
Downloading pycparser-3.0-py3-none-any.whl (48 kB)
Installing collected packages: pycparser, cffi, cryptography, oracledb
Successfully installed cffi-2.1.1 cryptography-50.0.1 oracledb-26.0.1 pycparser-3.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import oracledb

In [ ]:
import getpass
import oracledb

password = getpass.getpass("Oracle 비밀번호: ")

conn = oracledb.connect(
    user="SMALLBIZ",
    password=password,
    dsn="192.168.1.108:1521/ORCLPDB1"
)

print("Oracle DB 연결 성공!")

In [1]:
import socket

host = "192.168.1.108"
port = 1521

try:
    sock = socket.create_connection((host, port), timeout=5)
    print("1521 포트 연결 성공")
    sock.close()
except Exception as e:
    print("1521 포트 연결 실패:", e)

1521 포트 연결 성공

In [3]:
import getpass
import oracledb

password = getpass.getpass("Oracle 비밀번호: ")

conn = oracledb.connect(
    user="SMALLBIZ",
    password=password,
    dsn="192.168.1.108:1521/ORCLPDB1",
    tcp_connect_timeout=10
)

print("Oracle DB 연결 성공!")

Oracle DB 연결 성공!

In [5]:
import pandas as pd

customer_df = pd.read_sql("""
    SELECT *
    FROM CUSTOMER
""", conn)

print("CUSTOMER 데이터 크기:", customer_df.shape)
print("고객 수:", customer_df["CUSTOMER_ID"].nunique())

customer_df.head()

CUSTOMER 데이터 크기: (2000, 9)
고객 수: 2000

C:\Users\user\AppData\Local\Temp\ipykernel_5660\3511761938.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customer_df = pd.read_sql("""

,CUSTOMER_ID,REGION_CODE,INDUSTRY_ID,BASE_QUARTER_CODE,VIRTUAL_SALES_AMOUNT,SALES_GROWTH_RATE,HAS_LOAN,LOAN_TYPE,LOAN_BALANCE
0,C04_1689,11170510,6,20254,2160000,-12.74,1,운전자금대출,1400000
1,C04_2000,11740530,6,20254,4170000,-6.28,1,소상공인신용대출,2000000
2,C04_0468,11650660,2,20254,24340000,-18.70,0,없음,0
3,C04_0944,11170590,8,20254,5430000,16.72,0,없음,0
4,C04_0348,11560535,6,20254,26930000,22.03,1,운전자금대출,11500000

In [6]:
product_df = pd.read_sql("""
    SELECT *
    FROM FINANCIAL_PRODUCT
""", conn)

print("FINANCIAL_PRODUCT 데이터 크기:", product_df.shape)
print("금융상품 가입 건수:", len(product_df))

product_df.head()

C:\Users\user\AppData\Local\Temp\ipykernel_5660\2018311293.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  product_df = pd.read_sql("""

FINANCIAL_PRODUCT 데이터 크기: (6000, 5)
금융상품 가입 건수: 6000

  SUBSCRIPTION_ID CUSTOMER_ID PRODUCT_NAME    AMOUNT JOINED_DATE
0    SUB04_000480    C04_1645           예금  26060000  2025-01-05
1    SUB04_000481    C04_0680           예금  21600000  2022-07-11
2    SUB04_000482    C04_1596           적금   2020000  2025-01-24
3    SUB04_000483    C04_1687           펀드  23080000  2023-05-05
4    SUB04_000484    C04_0811           적금   3800000  2022-11-22

In [7]:
analysis_df = product_df.merge(
    customer_df,
    on="CUSTOMER_ID",
    how="left"
)

print("분석 데이터 크기:", analysis_df.shape)
print("고객 수:", analysis_df["CUSTOMER_ID"].nunique())
print("결측 고객 수:", analysis_df["REGION_CODE"].isna().sum())

analysis_df.head()

분석 데이터 크기: (6000, 13)
고객 수: 2000
결측 고객 수: 0

,SUBSCRIPTION_ID,CUSTOMER_ID,PRODUCT_NAME,AMOUNT,JOINED_DATE,REGION_CODE,INDUSTRY_ID,BASE_QUARTER_CODE,VIRTUAL_SALES_AMOUNT,SALES_GROWTH_RATE,HAS_LOAN,LOAN_TYPE,LOAN_BALANCE
0,SUB04_000480,C04_1645,예금,26060000,2025-01-05,11380560,10,20254,1000000,44.84,0,없음,0
1,SUB04_000481,C04_0680,예금,21600000,2022-07-11,11560535,6,20254,18480000,26.06,0,없음,0
2,SUB04_000482,C04_1596,적금,2020000,2025-01-24,11740685,1,20254,28240000,-3.52,0,없음,0
3,SUB04_000483,C04_1687,펀드,23080000,2023-05-05,11170690,2,20254,5650000,-1.90,0,없음,0
4,SUB04_000484,C04_0811,적금,3800000,2022-11-22,11710680,3,20254,34130000,7.97,0,없음,0

In [8]:
industry_df = pd.read_sql("""
    SELECT *
    FROM INDUSTRY
""", conn)

region_df = pd.read_sql("""
    SELECT *
    FROM REGION
""", conn)

print("INDUSTRY 컬럼:", industry_df.columns.tolist())
print("REGION 컬럼:", region_df.columns.tolist())

display(industry_df.head())
display(region_df.head())

INDUSTRY 컬럼: ['INDUSTRY_ID', 'INDUSTRY_NAME']
REGION 컬럼: ['REGION_CODE', 'REGION_NAME']

C:\Users\user\AppData\Local\Temp\ipykernel_5660\518851621.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  industry_df = pd.read_sql("""
C:\Users\user\AppData\Local\Temp\ipykernel_5660\518851621.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  region_df = pd.read_sql("""

   INDUSTRY_ID INDUSTRY_NAME
0            1         패션·잡화
1            2         음식·음료
2            3         미용·뷰티
3            4         여가·오락
4            5            숙박

   REGION_CODE REGION_NAME
0     11110515       청운효자동
1     11110530         사직동
2     11110540         삼청동
3     11110550         부암동
4     11110560         평창동

In [9]:
analysis_df = (
    analysis_df
    .merge(
        industry_df,
        on="INDUSTRY_ID",
        how="left"
    )
    .merge(
        region_df,
        on="REGION_CODE",
        how="left"
    )
)

print("최종 분석 데이터 크기:", analysis_df.shape)
print("업종명 결측:", analysis_df["INDUSTRY_NAME"].isna().sum())
print("지역명 결측:", analysis_df["REGION_NAME"].isna().sum())

analysis_df.head()

최종 분석 데이터 크기: (6000, 15)
업종명 결측: 0
지역명 결측: 0

,SUBSCRIPTION_ID,CUSTOMER_ID,PRODUCT_NAME,AMOUNT,JOINED_DATE,REGION_CODE,INDUSTRY_ID,BASE_QUARTER_CODE,VIRTUAL_SALES_AMOUNT,SALES_GROWTH_RATE,HAS_LOAN,LOAN_TYPE,LOAN_BALANCE,INDUSTRY_NAME,REGION_NAME
0,SUB04_000480,C04_1645,예금,26060000,2025-01-05,11380560,10,20254,1000000,44.84,0,없음,0,문화·취미·반려,구산동
1,SUB04_000481,C04_0680,예금,21600000,2022-07-11,11560535,6,20254,18480000,26.06,0,없음,0,자동차·운송서비스,영등포동
2,SUB04_000482,C04_1596,적금,2020000,2025-01-24,11740685,1,20254,28240000,-3.52,0,없음,0,패션·잡화,길동
3,SUB04_000483,C04_1687,펀드,23080000,2023-05-05,11170690,2,20254,5650000,-1.90,0,없음,0,음식·음료,서빙고동
4,SUB04_000484,C04_0811,적금,3800000,2022-11-22,11710680,3,20254,34130000,7.97,0,없음,0,미용·뷰티,잠실3동

In [10]:
print(analysis_df.columns.tolist())

['SUBSCRIPTION_ID', 'CUSTOMER_ID', 'PRODUCT_NAME', 'AMOUNT', 'JOINED_DATE', 'REGION_CODE', 'INDUSTRY_ID', 'BASE_QUARTER_CODE', 'VIRTUAL_SALES_AMOUNT', 'SALES_GROWTH_RATE', 'HAS_LOAN', 'LOAN_TYPE', 'LOAN_BALANCE', 'INDUSTRY_NAME', 'REGION_NAME']

In [11]:
for col in analysis_df.columns:
    print(col)

SUBSCRIPTION_ID
CUSTOMER_ID
PRODUCT_NAME
AMOUNT
JOINED_DATE
REGION_CODE
INDUSTRY_ID
BASE_QUARTER_CODE
VIRTUAL_SALES_AMOUNT
SALES_GROWTH_RATE
HAS_LOAN
LOAN_TYPE
LOAN_BALANCE
INDUSTRY_NAME
REGION_NAME

In [ ]:
# Pandas 고객 금융 분석

## 1. 상품별 이용 비중
금융상품별 가입 건수와 전체 가입 건 대비 이용 비중을 분석한다.

## 2. 업종별 평균 가입금액
업종별 금융상품 평균 가입금액을 비교한다.

## 3. 대출 보유 여부별 고객 비교
대출 보유 고객과 미보유 고객의 고객 수, 평균 매출,
평균 매출증감률을 비교한다.

In [12]:
# 1. 상품별 이용 비중

product_ratio = (
    analysis_df["PRODUCT_NAME"]
    .value_counts()
    .reset_index()
)

product_ratio.columns = ["상품명", "이용건수"]

product_ratio["이용비중(%)"] = (
    product_ratio["이용건수"]
    / product_ratio["이용건수"].sum()
    * 100
).round(2)

product_ratio

   상품명  이용건수  이용비중(%)
0   펀드  1705    28.42
1  ISA  1506    25.10
2   예금  1504    25.07
3   적금  1285    21.42

In [13]:
# 2. 업종별 평균 가입금액

industry_amount = (
    analysis_df
    .groupby("INDUSTRY_NAME")["AMOUNT"]
    .mean()
    .reset_index()
)

industry_amount.columns = ["업종", "평균가입금액"]

industry_amount["평균가입금액"] = (
    industry_amount["평균가입금액"]
    .round(0)
    .astype(int)
)

industry_amount = industry_amount.sort_values(
    "평균가입금액",
    ascending=False
)

industry_amount

           업종    평균가입금액
10      패션·잡화  20891276
2       미용·뷰티  20464598
8   자동차·운송서비스  20459589
7       음식·음료  20197396
5    식료품·편의소매  20132611
1    문화·취미·반려  19603656
6       여가·오락  19473055
0     가구·인테리어  18787720
9     전자기기·수리  18432464
3       생활서비스  18095899
4          숙박  17912769

In [14]:
# 3. 대출 보유 여부별 고객 비교

loan_compare = (
    customer_df
    .groupby("HAS_LOAN")
    .agg(
        고객수=("CUSTOMER_ID", "count"),
        평균매출=("VIRTUAL_SALES_AMOUNT", "mean"),
        평균매출증감률=("SALES_GROWTH_RATE", "mean")
    )
    .reset_index()
)

loan_compare["HAS_LOAN"] = loan_compare["HAS_LOAN"].map({
    0: "대출 미보유",
    1: "대출 보유"
})

loan_compare["평균매출"] = loan_compare["평균매출"].round(0)
loan_compare["평균매출증감률"] = loan_compare["평균매출증감률"].round(2)

loan_compare

  HAS_LOAN   고객수        평균매출  평균매출증감률
0   대출 미보유   990  42160505.0    11.91
1    대출 보유  1010  40875149.0     5.63

In [15]:
# 분석 결과 저장

product_ratio.to_csv(
    "product_ratio.csv",
    index=False,
    encoding="utf-8-sig"
)

industry_amount.to_csv(
    "industry_amount.csv",
    index=False,
    encoding="utf-8-sig"
)

loan_compare.to_csv(
    "loan_compare.csv",
    index=False,
    encoding="utf-8-sig"
)

print("분석 결과 저장 완료")

분석 결과 저장 완료